//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Category_Appearance {
            get {
                return ResourceManager.GetString("Category_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous.
        /// </summary>
        internal static string Category_Asynchronous {
            get {
                return ResourceManager.GetString("Category_Asynchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Category_Behavior {
            get {
                return ResourceManager.GetString("Category_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommandLink_RestingArrow {
            get {
                object obj = ResourceManager.GetObject("CommandLink_RestingArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommandLink_SelectedArrow {
            get {
                object obj = ResourceManager.GetObject("CommandLink_SelectedArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes an operation on a separate thread while showing a progress dialog..
        /// </summary>
        internal static string ProgressDialog_Description {
            get {
                return ResourceManager.GetString("ProgressDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handler to be run on a different thread when the operation begins..
        /// </summary>
        internal static string ProgressDialog_DoWork {
            get {
                return ResourceManager.GetString("ProgressDialog_DoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header text that indicates what general action is occurring..
        /// </summary>
        internal static string ProgressDialog_HeaderText {
            get {
                return ResourceManager.GetString("ProgressDialog_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The small text to show that can provide progress status..
        /// </summary>
        internal static string ProgressDialog_MessageText {
            get {
                return ResourceManager.GetString("ProgressDialog_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised when the worker thread indicates that some progress has been made..
        /// </summary>
        internal static string ProgressDialog_ProgressChanged {
            get {
                return ResourceManager.GetString("ProgressDialog_ProgressChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised when the worker has completed (either through success, failure, or cancellation)..
        /// </summary>
        internal static string ProgressDialog_RunWorkerCompleted {
            get {
                return ResourceManager.GetString("ProgressDialog_RunWorkerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title text that will show in the window title bar..
        /// </summary>
        internal static string ProgressDialog_TitleText {
            get {
                return ResourceManager.GetString("ProgressDialog_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the worker will report progress..
        /// </summary>
        internal static string ProgressDialog_WorkerReportsProgress {
            get {
                return ResourceManager.GetString("ProgressDialog_WorkerReportsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the worker supports cancellation..
        /// </summary>
        internal static string ProgressDialog_WorkerSupportsCancellation {
            get {
                return ResourceManager.GetString("ProgressDialog_WorkerSupportsCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafeDataReader cannot wrap an object of the same Type..
        /// </summary>
        internal static string SafeDataReader_NoRewrap {
            get {
                return ResourceManager.GetString("SafeDataReader_NoRewrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shield {
            get {
                object obj = ResourceManager.GetObject("Shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the text to display when the control is empty..
        /// </summary>
        internal static string TextBox_CueBannerDescription {
            get {
                return ResourceManager.GetString("TextBox_CueBannerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to show the cue banner when the control has focus..
        /// </summary>
        internal static string TextBox_ShowCueWhenFocusedDescription {
            get {
                return ResourceManager.GetString("TextBox_ShowCueWhenFocusedDescription", resourceCulture);
            }
        }
    }
}
